# Generated by Django 4.0.3 on 2022-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_contact_picture_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
