# Generated by Django 4.0.3 on 2022-03-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_contact_id_alter_contact_usn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='picture',
            new_name='pic',
        ),
    ]
