# Generated by Django 4.0.3 on 2022-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_picture_contact_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='usn',
            field=models.IntegerField(default=0),
        ),
    ]
