# Generated by Django 4.0.3 on 2022-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('bio', models.TextField(max_length=500)),
                ('j_role', models.CharField(choices=[('frontend_developer', 'frontend_developer'), ('php_developer', 'php_developer'), ('Python_Developer', 'Python_Developer'), ('Rails_Developer', 'Rails_Developer'), ('Web_Designer', 'Web_Designer'), ('WordPress_Developer', 'WordPress_Developer'), ('Android_Developer', 'Android_Developer'), ('iOS_Developer', 'iOS_Developer'), ('Mobile_Designer', 'Mobile_Designer'), ('Business_Owner', 'Business_Owner'), ('Freelancer', 'Freelancer'), ('Secretary', 'Secretary'), ('Maintenance', 'Maintenance')], max_length=500)),
                ('interests', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Business', 'Business')], max_length=500)),
            ],
        ),
    ]
