# Generated by Django 4.0.3 on 2022-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='picture',
        ),
        migrations.AlterField(
            model_name='form',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
