# Generated by Django 4.0.3 on 2022-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregform', '0003_alter_form_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='picture',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
